name: CI

on:
  push:
    branches: ['main', 'chore/ci']
  pull_request:
    branches: ['main', 'chore/ci']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [WebGL]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup cache
        uses: actions/cache@v5
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.platform }}
      - name: Upload artifact
        uses: actions/upload-artifact@v7
          with:
            name: Build
            path: build
